version: '3.8'

services:
  vue-pagemaker:
    build: .
    ports:
      - "8088:80"  # Changed from 3000:80 to avoid conflicts
    volumes:
      # Mount source code for hot reload
      - .:/usr/share/nginx/html
      # Mount nginx config
      - ./nginx.conf:/etc/nginx/nginx.conf
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health", "||", "exit", "1"]
      interval: 30s
      timeout: 10s
      retries: 3
    
  # Optional: Add a file watcher for automatic reload
  file-watcher:
    image: node:alpine
    working_dir: /app
    volumes:
      - .:/app
    command: >
      sh -c "
        npm install -g nodemon &&
        nodemon --watch js --watch index.html --exec 'echo File changed, reload browser' --delay 500ms
      "
    restart: unless-stopped 